server.port: 8090

spring.jackson:
  date-format: com.fasterxml.jackson.databind.util.StdDateFormat
  time-zone: Asia/Tokyo
  property-naming-strategy: SNAKE_CASE

spring.datasource.sql-script-encoding: utf-8

spring.security.oauth2.resourceserver.jwt:
  issuer-uri: http://localhost:9000/auth/realms/todo-api
  jwk-set-uri: http://localhost:9000/auth/realms/todo-api/protocol/openid-connect/certs

logging:
  level:
    org.springframework:
      security: trace
      jdbc.core.JdbcTemplate: debug